import localFont from "next/font/local";
import "./globals.css";
import { Box, Button, MenuItem, Stack } from '@chakra-ui/react'
import { Header } from './components/Header'
import { SubHeader } from './components/SubHeader'
import { Providers } from './providers'

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>



        <Providers>
          <Header></Header>
          <SubHeader/>
          {children}
        </Providers>
      </body>
    </html>
  );
}
